import type { Art } from "./types";
import { OUTLINE, SHADOW, WOOD, WOOD_DARK } from "./palette";

/** 48×32: spans three map columns and two rows. */
export const FARMHOUSE: Art = {
  palette: {
    o: OUTLINE,
    r: "#9e4935",
    R: "#733429",
    h: "#c0614a",
    c: "#8d8a80",
    C: "#6c6960",
    w: "#d7bd7b",
    W: "#b2915c",
    g: "#7cb4ae",
    G: "#c4e2d8",
    q: "#4b8381",
    d: "#73513a",
    D: "#5a3d2b",
    y: "#f2c45d",
    l: "#4f843e",
    p: "#e79bb0",
    k: WOOD,
    K: WOOD_DARK,
    S: "#a9a987",
    s: SHADOW,
  },
  rows: [
    "...............................ooooo............",
    "...............................occco............",
    "........ooooooooooooooooooooooooccCooooo........",
    "........ohrrrrrrrrrrrrrrrrrrrrrocccorrro........",
    ".......ohRRRRRRRRRRRRRRRRRRRRRRoCCcoRRRRo.......",
    ".......ohrrRrrrrrRrrrrrRrrrrrRrocccorrrro.......",
    "......ohrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrro......",
    "......ohRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRo......",
    ".....ohrrrrrRrrrrrRrrrrrRrrrrrRrrrrrRrrrrro.....",
    ".....ohrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrro.....",
    "....ohRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRo....",
    "....ohrrRrrrrrRrrrrrRrrrrrRrrrrrRrrrrrRrrrro....",
    "...ohrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrro...",
    "...oRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRo...",
    "..oooooooooooooooooooooooooooooooooooooooooooo..",
    "....oWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWo....",
    "....oWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWo....",
    "....owwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwo....",
    "....oWWWWoooooooooooWWWWWWWWWooooooooWWWWWWo....",
    "....owwwwoGGggoGgggowwwwwwwwwoddddddowowwwwo....",
    "....owwwwoGgggogggqowwwwwwwwwoddDdddoooowwwo....",
    "....oWWWWoooooooooooWWWWWWWWWoddDdddooyoWWWo....",
    "....owwwwoggggoGgggowwwwwwwwwoddDdddoooowwwo....",
    "....owwwwogggqoggqqowwwwwwwwwoDDDDDDowwwwwwo....",
    "....oWWWWoooooooooooWWWWWWWWWoddDdddoWWWWWWo....",
    "....owwwwplylplylplywwwwwwwwwoddDdydowwwwwwo....",
    "....owwwkkkkkkkkkkkkkwwwwwwwwoddDdddowwwwwwo....",
    "....oWWWKKKKKKKKKKKKKWWWWWWWWoddDdddoWWWWWWo....",
    "....owwwwwwwwwwwwwwwwwwwwwwwwoddddddowwwwwwo....",
    "....oooooooooooooooooooooooooooooooooooooooo....",
    ".....sssssssssssssssssssssssSSSSSSSSSSsssssss...",
    "......sssssssssssssssssssssssssssssssssssssss...",
  ],
};
