import type { Art } from "./types";
import { EYE, OUTLINE, SHADOW } from "./palette";

const base = { o: OUTLINE, E: EYE, _: SHADOW };

const wisp = {
  ...base,
  h: "#6f4b89",
  H: "#523769",
  s: "#e3c6e6",
  p: "#c98fc0",
  c: "#576aa1",
  C: "#354776",
  b: "#3d3a5c",
  F: "#2b2320",
};

export const WISP = {
  south: {
    palette: wisp,
    rows: [
      "........oo......",
      ".....ooohho.....",
      "....ohhhhhho....",
      "...ohhhhhhhho...",
      "...ohhHHHHhho...",
      "...ohHssssHho...",
      "...ohsEssEsho...",
      "...ohsEssEsho...",
      "...ohpsssspho...",
      "....ohhsshho....",
      "...occcccccco...",
      "...oscccccCso...",
      "....occcccCo....",
      "....obboobbo....",
      "....oFFooFFo....",
      "...__oo__oo__...",
    ],
  },
  north: {
    palette: wisp,
    rows: [
      "........oo......",
      ".....ooohho.....",
      "....ohhhhhho....",
      "...ohhhhhhhho...",
      "...ohhhhhhhho...",
      "...ohhhhhhhho...",
      "...ohhhhhhhho...",
      "...ohhhhhhHho...",
      "...ohhhhhhHho...",
      "....ohhhhhho....",
      "...occcccccco...",
      "...oscccccCso...",
      "....occcccCo....",
      "....obboobbo....",
      "....oFFooFFo....",
      "...__oo__oo__...",
    ],
  },
  west: {
    palette: wisp,
    rows: [
      ".........oo.....",
      "......oooohho...",
      "....ohhhhhhho...",
      "...ohhhhhhhho...",
      "...oHHHhhhhho...",
      "...osssHhhhho...",
      "...osEsshhhho...",
      "...osEsshhhho...",
      "...ospsshhhho...",
      "....ossshhho....",
      "....occcccco....",
      "....oscccCco....",
      "....occccCco....",
      "....obboobbo....",
      "....oFFooFFo....",
      "...__oo__oo__...",
    ],
  },
} satisfies Record<string, Art>;

export const MIRA: Art = {
  palette: {
    ...base,
    h: "#5a392b",
    g: "#6ea34f",
    s: "#e5ad78",
    p: "#e08a6a",
    c: "#d68047",
    C: "#a85239",
    a: "#f1e2bb",
    b: "#6b4a33",
    F: "#3d2a20",
  },
  rows: [
    "................",
    ".....oooooo.....",
    "....ohhhhhho....",
    "...ohhhhhhgho...",
    "...ohhhhhhhho...",
    "...ohhsssshho...",
    "...ohsEssEsho...",
    "...ohsEssEsho...",
    "..ohhpssssphho..",
    "..oho.osso.oho..",
    "...occcccccco...",
    "...oscaaaacso...",
    "....ocaaaaCo....",
    "....obboobbo....",
    "....oFFooFFo....",
    "...__oo__oo__...",
  ],
};

export const BRAMBLE: Art = {
  palette: {
    ...base,
    h: "#5f8a3f",
    H: "#3f6a3b",
    l: "#8fbf5a",
    s: "#a57a57",
    p: "#b86a52",
    m: "#5a3a2a",
    c: "#678f4c",
    C: "#3f6a3b",
    t: "#8a5a34",
    b: "#5a4632",
    F: "#3d2a20",
  },
  rows: [
    "................",
    "......oooo......",
    ".....ohhlho.....",
    "....ohhlhhho....",
    "..ohhhhhhhhhho..",
    "..oHHHHHHHHHHo..",
    "...osssssssso...",
    "...osEssssEso...",
    "...opssmmsspo...",
    "....oossssoo....",
    "...occcccccco...",
    "...oscCccCcso...",
    "....occttcco....",
    "....obboobbo....",
    "....oFFooFFo....",
    "...__oo__oo__...",
  ],
};

export const NORI: Art = {
  palette: {
    ...base,
    h: "#d8c15e",
    H: "#a8913a",
    s: "#c98f67",
    p: "#b0705a",
    c: "#4e8ba0",
    C: "#326477",
    b: "#34505e",
    F: "#26343d",
  },
  rows: [
    "................",
    "................",
    ".....oooooo.....",
    "....ohhhhhho....",
    "...ohhhhhhhho...",
    "..ohhhhhhhhhho..",
    "..oHHHHHHHHHHo..",
    "...osEssssEso...",
    "...opsssssspo...",
    "....oossssoo....",
    "...occcccccco...",
    "...oscccccCso...",
    "...occcccccCo...",
    "....obboobbo....",
    "....oFFooFFo....",
    "...__oo__oo__...",
  ],
};

export const TANSY: Art = {
  palette: {
    ...base,
    h: "#75472f",
    s: "#d8a06e",
    p: "#d0705f",
    m: "#7a3a36",
    c: "#a65367",
    C: "#793a50",
    a: "#f1e2bb",
    b: "#5a3444",
    F: "#3d2a20",
  },
  rows: [
    "......oooo......",
    ".....ohhhho.....",
    "....oohhhhoo....",
    "...ohhhhhhhho...",
    "...ohhhhhhhho...",
    "...ohssssssho...",
    "...osEssssEso...",
    "...osEssssEso...",
    "...opssmmsspo...",
    "....oossssoo....",
    "...occcccccco...",
    "...oscaaaacso...",
    "....oaaaaaao....",
    "....obboobbo....",
    "....oFFooFFo....",
    "...__oo__oo__...",
  ],
};
