import type { Art } from "./types";
import {
  LEAF,
  LEAF_DARK,
  LEAF_LIGHT,
  OUTLINE,
  TURNIP,
  TURNIP_PINK,
  TURNIP_PINK_DARK,
  TURNIP_SHADE,
} from "./palette";

const turnip = {
  L: LEAF_LIGHT,
  l: LEAF,
  D: LEAF_DARK,
  m: "rgba(60, 35, 20, 0.35)",
  o: OUTLINE,
  t: TURNIP,
  s: TURNIP_SHADE,
  p: TURNIP_PINK,
  P: TURNIP_PINK_DARK,
};

/** Transparent overlays drawn on a soil tile, indexed by plot stage 0-3. */
export const TURNIP_STAGES: readonly Art[] = [
  {
    palette: turnip,
    rows: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "........L.......",
      ".......lL.......",
      "......mmmm......",
      "................",
      "................",
      "................",
    ],
  },
  {
    palette: turnip,
    rows: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "....LL....LL....",
      "...LllL..LllL...",
      "....lllDDlll....",
      "......lDDl......",
      ".......DD.......",
      ".......DD.......",
      "......mmmm......",
      "................",
      "................",
      "................",
    ],
  },
  {
    palette: turnip,
    rows: [
      "................",
      "................",
      ".......LL.......",
      "...LL..LlL..LL..",
      "..LllL.Lll.LllL.",
      "..lllllDllDllll.",
      "...lllDDlDDlll..",
      "....llDDDDDll...",
      "......DDDD......",
      "......oppo......",
      ".....otttto.....",
      "......otto......",
      ".....mmmmmm.....",
      "................",
      "................",
      "................",
    ],
  },
  {
    palette: turnip,
    rows: [
      "......L..L......",
      "..LL.LlL.LlL.LL.",
      ".LllLLllLllLLllL",
      ".llllllDlDllllll",
      "..lllDDlDDDlll..",
      "...llDDDDDDll...",
      ".....DDDDDD.....",
      ".....oppppo.....",
      "....opPppPpo....",
      "...optttttPpo...",
      "...otttttttso...",
      "...ottttttsso...",
      "....ottttsso....",
      ".....ossso......",
      "......oto.......",
      "................",
    ],
  },
];
