import type { Art } from "./types";
import {
  BERRY,
  BERRY_DARK,
  BERRY_SHINE,
  EYE,
  FISH,
  FISH_BELLY,
  FISH_DARK,
  LEAF,
  LEAF_DARK,
  LEAF_LIGHT,
  OUTLINE,
  TURNIP,
  TURNIP_PINK,
  TURNIP_PINK_DARK,
  TURNIP_SHADE,
  WOOD,
  WOOD_DARK,
  WOOD_LIGHT,
} from "./palette";

export const SEEDS: Art = {
  palette: {
    o: OUTLINE,
    k: "#b08a52",
    K: "#8a6838",
    y: "#d8c15e",
    s: "#6f5431",
  },
  rows: [
    "................",
    "................",
    ".......oo.......",
    "......okko......",
    ".....oyyyyo.....",
    "......okko......",
    ".....okkkko.....",
    "....okkkkkko....",
    "...okkkkkkkKo...",
    "...okkksskkKo...",
    "...okkssssKKo...",
    "...okkksskkKo...",
    "...oKkkkkkKKo...",
    "....oKKKKKKo....",
    ".....s..s.s.....",
    "................",
  ],
};

export const TURNIPS: Art = {
  palette: {
    o: OUTLINE,
    L: LEAF_LIGHT,
    l: LEAF,
    D: LEAF_DARK,
    t: TURNIP,
    s: TURNIP_SHADE,
    p: TURNIP_PINK,
    P: TURNIP_PINK_DARK,
  },
  rows: [
    "................",
    ".....L...L......",
    "....LlL.LlL.....",
    ".....lDLDl......",
    "......DDD.......",
    ".....opppo......",
    "....opPpppo.....",
    "...optttPpso....",
    "..otttttttsso...",
    "..ottttttttso...",
    "..otttttttsso...",
    "...otttttsso....",
    "....ottsso......",
    ".....oso........",
    "......o.........",
    "................",
  ],
};

export const BERRIES: Art = {
  palette: {
    o: OUTLINE,
    b: BERRY,
    B: BERRY_DARK,
    s: BERRY_SHINE,
    L: LEAF_LIGHT,
    l: LEAF,
    D: LEAF_DARK,
  },
  rows: [
    "................",
    "................",
    "..........LL....",
    ".........LllL...",
    "........DLlL....",
    ".......D..ooo...",
    "..ooo..D.osbbo..",
    ".osbbo.D.obbbo..",
    ".obbbo...obbBo..",
    ".obbBoooo.ooo...",
    "..oooosbbo......",
    ".....obbbo......",
    ".....obbBo......",
    "......ooo.......",
    "................",
    "................",
  ],
};

export const FISH_ITEM: Art = {
  palette: {
    o: OUTLINE,
    F: FISH,
    d: FISH_DARK,
    y: FISH_BELLY,
    E: EYE,
    W: "#fff7e0",
  },
  rows: [
    "................",
    "................",
    "................",
    "................",
    "................",
    ".....oooooo.....",
    "...ooFFFdFFoo..o",
    "..oWEFFFddFFFooo",
    ".oFFFFFFFFFFFFdo",
    ".ooyyyyyyFFFFFdo",
    "..oyyyyyyyFFooFo",
    "...ooyyyyyoo..oo",
    ".....oooooo.....",
    "................",
    "................",
    "................",
  ],
};

export const WOOD_ITEM: Art = {
  palette: {
    o: OUTLINE,
    k: WOOD,
    K: WOOD_DARK,
    L: WOOD_LIGHT,
    R: "#d9b27a",
    l: LEAF_LIGHT,
    D: LEAF_DARK,
  },
  rows: [
    "................",
    "................",
    "................",
    "................",
    ".......ll.......",
    ".......oD.......",
    "..ooooooooooooo.",
    ".okkKkkkkkkkoRRo",
    ".okkkkkKkkkkoRLo",
    ".oKKkkkkkKkkoLRo",
    ".oKKKKKKKKKKoRRo",
    "..ooooooooooooo.",
    "................",
    "................",
    "................",
    "................",
  ],
};
