import type { Art } from "./types";
import { EYE, EYE_SHINE, OUTLINE } from "./palette";

/** 24×24 chat-panel busts. */
export const MIRA_PORTRAIT: Art = {
  palette: {
    o: OUTLINE,
    E: EYE,
    W: EYE_SHINE,
    b: "#9fc269",
    h: "#5a392b",
    g: "#6ea34f",
    G: "#9fd37a",
    s: "#e5ad78",
    p: "#e08a6a",
    m: "#9a4f3a",
    c: "#d68047",
    C: "#a85239",
    a: "#f1e2bb",
  },
  rows: [
      "bbbbbbbbbbbbbbbbbbbbbbbb",
      "bbbbbbbbbbbbbbbbbbbbbbbb",
      "bbbbbbbboooooooobbbbbbbb",
      "bbbbbboohhhhhhhhGobbbbbb",
      "bbbbbohhhhhhhhhgggobbbbb",
      "bbbbohhhhhhhhhhhgghobbbb",
      "bbbbohhhhhhhhhhhhhhobbbb",
      "bbbbohhhhsssssshhhhobbbb",
      "bbbbohhsssssssssshhobbbb",
      "bbbbohsssssssssssshobbbb",
      "bbbbossEEssssssEEssobbbb",
      "bbbbossEWssssssEWssobbbb",
      "bbbbossEEssssssEEssobbbb",
      "bbbbosppssssssssppsobbbb",
      "bbbbossssssmmssssssobbbb",
      "bbbbbossssssssssssobbbbb",
      "bbbbbboossssssssoobbbbbb",
      "bbbbbbbboossssoobbbbbbbb",
      "bbbbooooccssssccoooobbbb",
      "bbboccccoaaaaaaoccccobbb",
      "bboCcccccaaaaaacccccCobb",
      "boCccccccaaaaaaccccccCob",
      "boCccccccaaaaaaccccccCob",
      "boCccccccaaaaaaccccccCob",
  ],
};

export const BRAMBLE_PORTRAIT: Art = {
  palette: {
    o: OUTLINE,
    E: EYE,
    W: EYE_SHINE,
    b: "#7d9c59",
    h: "#5f8a3f",
    H: "#3f6a3b",
    l: "#8fbf5a",
    s: "#a57a57",
    p: "#b86a52",
    m: "#5a3a2a",
    c: "#678f4c",
    C: "#3f6a3b",
    t: "#8a5a34",
  },
  rows: [
      "bbbbbbbbbbbbbbbbbbbbbbbb",
      "bbbbbboooooooooooobbbbbb",
      "bbbbbbohhhlhhhhhhobbbbbb",
      "bbbbbbohlhhhlhhlhobbbbbb",
      "bbbbboohhhhhhhhhhoobbbbb",
      "bbbbohollllllllllohobbbb",
      "bbohhhhhhhhhhhhhhhhhhobb",
      "bboooooooooooooooooooobb",
      "bbbbHHHHHHHHHHHHHHHHbbbb",
      "bbbbohsssssssssssshobbbb",
      "bbbbossEEssssssEEssobbbb",
      "bbbbossEWssssssEWssobbbb",
      "bbbbossEEssssssEEssobbbb",
      "bbbbosppssssssssppsobbbb",
      "bbbbossssssmmssssssobbbb",
      "bbbbbossssssssssssobbbbb",
      "bbbbbboossssssssoobbbbbb",
      "bbbbbbbboossssoobbbbbbbb",
      "bbbbooooccssssccoooobbbb",
      "bbbocccccccttcccccccobbb",
      "bboCcccccccttcccccccCobb",
      "boCccccccccttccccccccCob",
      "boCccccccccttccccccccCob",
      "boCccccccccttccccccccCob",
  ],
};

export const NORI_PORTRAIT: Art = {
  palette: {
    o: OUTLINE,
    E: EYE,
    W: EYE_SHINE,
    b: "#5d9caf",
    h: "#d8c15e",
    H: "#a8913a",
    s: "#c98f67",
    p: "#b0705a",
    m: "#6b3f2e",
    c: "#4e8ba0",
    C: "#326477",
    y: "#d8c15e",
  },
  rows: [
      "bbbbbbbbbbbbbbbbbbbbbbbb",
      "bbbbbbboooooooooobbbbbbb",
      "bbbbbbbohhhhhhhhobbbbbbb",
      "bbbbbboohhhhhhhhoobbbbbb",
      "bbbbbohohhhhhhhhohobbbbb",
      "bbohhhhhhhhhhhhhhhhhhobb",
      "bboooooooooooooooooooobb",
      "bbbbHHHHHHHHHHHHHHHHbbbb",
      "bbbbohhsssssssssshhobbbb",
      "bbbbohsssssssssssshobbbb",
      "bbbbossEEssssssEEssobbbb",
      "bbbbossEWssssssEWssobbbb",
      "bbbbossEEssssssEEssobbbb",
      "bbbbosppssssssssppsobbbb",
      "bbbbossssssmmssssssobbbb",
      "bbbbbossssssssssssobbbbb",
      "bbbbbboossssssssoobbbbbb",
      "bbbbbbbboossssoobbbbbbbb",
      "bbbbooooccssssccoooobbbb",
      "bbboccccccCcccccccccobbb",
      "bboCccccccCyycccccccCobb",
      "boCcccccccCccccccccccCob",
      "boCcccccccCyyccccccccCob",
      "boCcccccccCccccccccccCob",
  ],
};

export const TANSY_PORTRAIT: Art = {
  palette: {
    o: OUTLINE,
    E: EYE,
    W: EYE_SHINE,
    b: "#b46b79",
    h: "#75472f",
    H: "#5a3524",
    g: "#e0c35a",
    s: "#d8a06e",
    p: "#d0705f",
    m: "#7a3a36",
    c: "#a65367",
    C: "#793a50",
    a: "#f1e2bb",
  },
  rows: [
      "bbbbbbbbboooooobbbbbbbbb",
      "bbbbbbbbohhHHhhobbbbbbbb",
      "bbbbbbbboggggggobbbbbbbb",
      "bbbbbboohhhhhhhhoobbbbbb",
      "bbbbbohhhhhhhhhhhhobbbbb",
      "bbbbohhhhhhhhhhhhhhobbbb",
      "bbbbohhhhhhhhhhhhhhobbbb",
      "bbbbohhhhsssssshhhhobbbb",
      "bbbbohhsssssssssshhobbbb",
      "bbbbohsssssssssssshobbbb",
      "bbbbossEEssssssEEssobbbb",
      "bbbbossEWssssssEWssobbbb",
      "bbbbossEEssssssEEssobbbb",
      "bbbbosppssssssssppsobbbb",
      "bbbbossssssmmssssssobbbb",
      "bbbbbossssssssssssobbbbb",
      "bbbbbboossssssssoobbbbbb",
      "bbbbbbbboossssoobbbbbbbb",
      "bbbbooooccssssccoooobbbb",
      "bbboccccoaaaaaaoccccobbb",
      "bboCcccccaaaaaacccccCobb",
      "boCccccccaaaaaaccccccCob",
      "boCccccccaaaaaaccccccCob",
      "boCccccccaaaaaaccccccCob",
  ],
};

export const LANTERN_SPIRIT_PORTRAIT: Art = {
  palette: {
    o: "#45303d",
    b: "#433f69",
    f: "#eac763",
    F: "#cb7749",
    y: "#fff0a8",
    E: "#45303d",
    m: "#7a3a36",
    p: "#f0a070",
    e: "#f3db83",
    d: "#2f2d4e",
  },
  rows: [
      "bbbbbbbbbbboobbbbbbbbbbb",
      "bbbbbbbbbbboobbbbbbbbbbb",
      "bbbbbbbbbboffobbbbebbbbb",
      "bbbbbbbbbboffobbbbbbbbbb",
      "bbbebbbbboffffobbbbbbbbb",
      "bbbbbbbboffffffobbbbbbbb",
      "bbbbbbbbofffFFFobbbbbbbb",
      "bbbbbbbofffffFFFobbbebbb",
      "bbbbbbofyyffffFFFobbbbbb",
      "bbbbbbofyyffffFFFobbbbbb",
      "bbbbbofyyEffffEFFFobbbbb",
      "bbbbbofyyEffffEFFFobbbbb",
      "bbbbbofypffffffpFFobbbbb",
      "bbbbbofyyffmmffFFFobbbbb",
      "bbbbbofyyffffffFFFobbbbb",
      "bbbbbbofyyffffFFFobbbbbb",
      "bbebbbofyyffffFFFobbbbbb",
      "bbbbbbbofyyffFFFobbbbbbb",
      "bbbbbbbbofffFFFobbbbbebb",
      "bbbbbbbbbboffobbbbbbbbbb",
      "bbbbbbbbbboooobbbbbbbbbb",
      "bbbbbbbddddddddddbbbbbbb",
      "bbbbbbbbddddddddbbbbbbbb",
      "bbbbbbbbbbbbbbbbbbbbbbbb",
  ],
};
