import type { Art } from "./types";
import {
  CREAM,
  GRASS,
  GRASS_DARK,
  GRASS_LIGHT,
  LEAF_DARK,
  OUTLINE,
  TURNIP_PINK,
  WATER,
  WATER_DARK,
  WATER_LIGHT,
  WATER_SHINE,
  WOOD,
  WOOD_DARK,
  BERRY,
  FISH,
} from "./palette";

const grass = { g: GRASS, d: GRASS_DARK, l: GRASS_LIGHT };

export const GRASS_TUFTS: Art = {
  palette: grass,
  rows: [
    "gggggggggggggggg",
    "gggggggggggggldg",
    "gggdgdgggggggggg",
    "gggdddgggggggggg",
    "gggggggggggggggg",
    "gggggggggggggggg",
    "ggggggggggdgdggg",
    "glggggggggdddggg",
    "gggggggggggggggg",
    "gggggggggggggggg",
    "ggggggldgggggggg",
    "gggggggggggggggg",
    "ggdgdgggggggggdg",
    "ggdddggggggglgdg",
    "gggggggggggggggg",
    "gggggggggggggggg",
  ],
};

export const GRASS_FLOWERS: Art = {
  palette: { ...grass, f: CREAM, y: "#f2c45d", p: "#e79bb0" },
  rows: [
    "gggggggggggggggg",
    "gggggggggggggggg",
    "ggggfggggggggggg",
    "gggfyfggggggdggg",
    "ggggfgggggggdggg",
    "ggggdggggggggggg",
    "gggggggggggggggg",
    "gggggggggggpgggg",
    "ggggggggggpypggg",
    "gldggggggggpgggg",
    "gggggggggggdgggg",
    "gggggggggggggggg",
    "gggggggdgdgggggg",
    "gggggggdddggggfg",
    "gggggggggggggfyf",
    "ggggggggggggggfg",
  ],
};

export const GRASS_STONES: Art = {
  palette: { ...grass, s: "#a9a987", S: "#7b7f5e" },
  rows: [
    "gggggggggggggggg",
    "ggggggggdggggggg",
    "gggggggggggggggg",
    "gggggggggggggggg",
    "gggggggggggssggg",
    "ggglggggggsssSgg",
    "ggggggggggdSSdgg",
    "gggggggggggggggg",
    "gggggggggggggggg",
    "gdgdgggggggggggg",
    "gdddgggggggggggg",
    "ggggggggggggglgg",
    "gggggsgggggggggg",
    "ggggsSdggggggggg",
    "gggggggggggggggg",
    "gggggggggggggggg",
  ],
};

/** Repeated entries weight how often each variant is scattered. */
export const GRASS_TILES = [GRASS_TUFTS, GRASS_TUFTS, GRASS_STONES, GRASS_FLOWERS] as const;

export const DIRT_PATH: Art = {
  palette: { p: "#c3a86a", l: "#d3bb7c", d: "#a88b57", k: "#8f7248" },
  rows: [
    "pppppppppppppppp",
    "ppplppppppppppdp",
    "ppppppppppppppkp",
    "pppppppdlppppppp",
    "pppppppkdppppppp",
    "pdpppppppppppppp",
    "pppppppppppplppp",
    "pppppppppppppppp",
    "pppplppppppppppp",
    "ppppppppppdlpppp",
    "ppdppppppppkpppp",
    "ppkppppppppppppp",
    "pppppppppppppppp",
    "pppppppplppppdpp",
    "pppppppppppppppp",
    "pppdpppppppppppp",
  ],
};

const water = { w: WATER, l: WATER_LIGHT, s: WATER_SHINE, d: WATER_DARK };

export const WATER_FRAMES: readonly Art[] = [
  {
    palette: water,
    rows: [
      "wwwwwwwwwwwwwwww",
      "wwwwwwwwwwwwwwww",
      "wwwlsslwwwwwwwww",
      "wwwwwwwwwwwwwwww",
      "wwwwwwwwwwwwwddw",
      "wwwwwwwwwlsslwww",
      "wddwwwwwwwwwwwww",
      "wwwwwwwwwwwwwwww",
      "wwwwwwwwwwwwwwww",
      "wwwwwlsslwwwwwww",
      "wwwwwwwwwwwwwwww",
      "wwwwwwwwwwwwddww",
      "wlslwwwwwwwwwwww",
      "wwwwwwwwwwwlsslw",
      "wwwwwddwwwwwwwww",
      "wwwwwwwwwwwwwwww",
    ],
  },
  {
    palette: water,
    rows: [
      "wwwwwwwwwwwwwwww",
      "wwwwwwwwwwwwwwww",
      "wwwwwlsslwwwwwww",
      "wwwwwwwwwwwwwwww",
      "wwwwwwwwwwwwwddw",
      "wwwwwwwlsslwwwww",
      "wddwwwwwwwwwwwww",
      "wwwwwwwwwwwwwwww",
      "wwwwwwwwwwwwwwww",
      "wwwwwwwlsslwwwww",
      "wwwwwwwwwwwwwwww",
      "wwwwwwwwwwwwddww",
      "wwwlslwwwwwwwwww",
      "wwwwwwwwwlsslwww",
      "wwwwwddwwwwwwwww",
      "wwwwwwwwwwwwwwww",
    ],
  },
];

export const SOIL_DRY: Art = {
  palette: { b: "#785338", s: "#9b6742", l: "#b57b4f", f: "#75472f", k: "#86573a" },
  rows: [
    "bbbbbbbbbbbbbbbb",
    "bllllllllllllllb",
    "bssssssssskssssb",
    "bssksssssssssssb",
    "bffffffffffffffb",
    "bllllllllllllllb",
    "bssssskssssssssb",
    "bssssssssssskssb",
    "bffffffffffffffb",
    "bllllllllllllllb",
    "bskssssssssssssb",
    "bssssssssksssssb",
    "bffffffffffffffb",
    "bllllllllllllllb",
    "bssssssssssssssb",
    "bbbbbbbbbbbbbbbb",
  ],
};

export const SOIL_WET: Art = {
  palette: { b: "#57392a", s: "#6e4a32", l: "#835a3d", f: "#4f3322", k: "#5f3f2b", w: "#8fb6b4" },
  rows: [
    "bbbbbbbbbbbbbbbb",
    "bllllllllllllllb",
    "bssssssssskssssb",
    "bssksssswssssssb",
    "bffffffffffffffb",
    "bllllllllllllllb",
    "bssssskssssssssb",
    "bswssssssssksssb",
    "bffffffffffffffb",
    "bllllllllllllllb",
    "bsksssssssswsssb",
    "bssssssssksssssb",
    "bffffffffffffffb",
    "bllllllllllllllb",
    "bsssswsssssssssb",
    "bbbbbbbbbbbbbbbb",
  ],
};

export const TREE: Art = {
  palette: {
    f: "#466f3d",
    d: "#3a5e34",
    o: "#1f3a25",
    c: "#315c37",
    l: "#51824a",
    D: "#24462d",
    t: "#66432e",
    T: "#4a3021",
  },
  rows: [
    "fffffoooooofffff",
    "fffoollccccoofff",
    "ffollllccccccoff",
    "folllcccccccccof",
    "follcccccccccDof",
    "olllccccccccccDo",
    "olcccccccccccDDo",
    "occccccccccccDDo",
    "focccccccccDDDof",
    "foDccccccDDDDDof",
    "ffoDDDDDDDDDDoff",
    "fffoooooooooofff",
    "ffffffotTofffffd",
    "fdffffotToffffff",
    "ffffddotTodddfff",
    "fffffddddddfffff",
  ],
};

export const MARKET: Art = {
  palette: {
    b: "#b99b63",
    s: "#a4864f",
    o: OUTLINE,
    r: "#b8483a",
    R: "#8a352c",
    w: CREAM,
    W: "#d4c08e",
    t: WOOD_DARK,
    k: WOOD,
    K: WOOD_DARK,
    n: TURNIP_PINK,
    e: BERRY,
    f: FISH,
    g: LEAF_DARK,
  },
  rows: [
    "bbbbbbbbbbbbbbbb",
    "boooooooooooooob",
    "orrwwrrwwrrwwrro",
    "orrwwrrwwrrwwrro",
    "oRRWWRRWWRRWWRRo",
    "boRooRooRooRooob",
    "bbtbbbbbbbbbbtbb",
    "bbtbbgbbbbbbbtbb",
    "bbtbnnbeebffbtbb",
    "boooooooooooooob",
    "okkkkkkkkkkkkkko",
    "okKkkKkkKkkKkkKo",
    "okKkkKkkKkkKkkKo",
    "oKKKKKKKKKKKKKKo",
    "boooooooooooooob",
    "bssssssssssssssb",
  ],
};
